#!/usr/bin/env python3
"""Generates Meta_Bible_Data/sqlite/versions/<edition>.sql from the flat-file corpora.

Rerun after any edit to the flat-file corpora; the .sql files are the
git-trackable, text-diffable stand-in for committing the bulk verse data
as a binary blob.

Edition metadata is declared in Meta_Bible_Data/sqlite/editions.json. Verse ordering and GOI
numbers come from GOI_bible.sqlite3 when that edition already exists; new
editions can use a template_edition for numbering while reading their own
flatfiles.
"""
import argparse
import json
import os
import sqlite3
import sys

META_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(META_ROOT)
DB = os.path.join(META_ROOT, "local_backups", "GOI_bible.sqlite3")
SQLITE_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SQLITE_DIR, "versions")
CATALOG = os.path.join(SQLITE_DIR, "editions.json")


def sql_quote(s):
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def load_catalog():
    with open(CATALOG, encoding="utf-8") as handle:
        editions = json.load(handle)
    seen = set()
    for edition in editions:
        edition_id = edition["edition_id"]
        if edition_id in seen:
            raise SystemExit(f"duplicate edition_id in {CATALOG}: {edition_id}")
        seen.add(edition_id)
    return editions


def selected_editions(catalog, requested):
    if not requested:
        return catalog
    by_id = {edition["edition_id"]: edition for edition in catalog}
    missing = [edition_id for edition_id in requested if edition_id not in by_id]
    if missing:
        raise SystemExit(f"unknown edition(s): {', '.join(missing)}")
    return [by_id[edition_id] for edition_id in requested]


def metadata_rows(cur, edition):
    edition_id = edition["edition_id"]
    row_count = cur.execute("SELECT COUNT(*) FROM verses WHERE edition_id=?", (edition_id,)).fetchone()[0]
    if row_count:
        rows = cur.execute(
            "SELECT goi, conical, book, chapter, verse, testament "
            "FROM verses WHERE edition_id=? ORDER BY goi",
            (edition_id,),
        ).fetchall()
        return rows

    template = edition.get("template_edition")
    if not template:
        raise SystemExit(
            f"{edition_id} has no rows in GOI_bible.sqlite3 and no template_edition in {CATALOG}"
        )
    rows = cur.execute(
        "SELECT goi, conical, book, chapter, verse, testament "
        "FROM verses WHERE edition_id=? ORDER BY goi",
        (template,),
    ).fetchall()
    if not rows:
        raise SystemExit(f"{edition_id} template_edition {template} has no rows")
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("editions", nargs="*", help="optional edition_id list; default builds every catalog edition")
    args = parser.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    catalog = selected_editions(load_catalog(), args.editions)
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    total = 0
    for edition in catalog:
        edition_id = edition["edition_id"]
        rel_dir = edition["flatfile_dir"]
        d = os.path.join(ROOT, rel_dir)
        rows = metadata_rows(cur, edition)
        suffix = edition.get("filename_suffix", edition_id)
        version = edition.get("version", edition_id)
        lang = edition["language_subtag"]

        values = []
        missing = 0
        for goi, conical, book, chapter, verse, testament in rows:
            fn = f"{conical:03d}_{book}_{chapter:03d}_{verse:03d}_{suffix}.txt"
            fp = os.path.join(d, fn)
            if not os.path.isfile(fp):
                missing += 1
                continue
            with open(fp, encoding="utf-8") as f:
                text = f.read().strip()
            values.append(
                "({}, {}, {}, {}, {}, {}, {}, {}, {}, {})".format(
                    goi, conical, sql_quote(edition_id), sql_quote(version),
                    sql_quote(lang), sql_quote(book), chapter, verse,
                    sql_quote(testament), sql_quote(text),
                )
            )

        if missing:
            print(f"WARNING: {edition_id}: {missing} rows had no matching flat file", file=sys.stderr)

        out_path = os.path.join(OUT_DIR, f"{edition_id}.sql")
        with open(out_path, "w", encoding="utf-8") as out:
            out.write(f"-- {edition_id}: {len(values)} verses. Generated by sqlite/build_buffet.py\n")
            out.write("INSERT INTO verses (goi, conical, edition_id, version, language_subtag, book, chapter, verse, testament, verse_text) VALUES\n")
            out.write(",\n".join(values))
            out.write(";\n")

        print(f"{edition_id}: wrote {len(values)} rows -> {out_path}")
        total += len(values)

    conn.close()
    print(f"TOTAL: {total}")


if __name__ == "__main__":
    main()
