#!/usr/bin/env python3
"""Generates sqlite/versions/<edition>.sql from the flat-file corpora.

Rerun after any edit to the flat-file corpora; the .sql files are the
git-trackable, text-diffable stand-in for committing the bulk verse data
as a binary blob.

goi/conical/language_subtag are read from the existing GOI_bible.sqlite3
(still the authoritative source for that numbering), not re-derived.
"""
import os
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "GOI_bible.sqlite3")
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "versions")

DIRS = {
    "KJV": "English_Bible_KJV/One_Directory_KJV",
    "WEBUS": "English_Bible_WEBUS/One_Directory_WEBUS",
    "TR1550": "Greek_Bible_TR1550/One_Directory_TR1550",
    "WLC": "Hebrew_Bible_WLC/One_Directory_WLC_KJV",
    "GOI_En": "GOI_Bible_English",
    "GOI_Zh_Hant": "GOI_Bible_Chinese_Hant",
    "GOI_Zh_Hans": "GOI_Bible_Chinese_Hans",
}


def sql_quote(s):
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    total = 0
    for edition_id, rel_dir in DIRS.items():
        d = os.path.join(ROOT, rel_dir)
        rows = cur.execute(
            "SELECT goi, conical, version, language_subtag, book, chapter, verse, testament "
            "FROM verses WHERE edition_id=? ORDER BY conical, chapter, verse",
            (edition_id,),
        ).fetchall()

        # filename suffix matches the edition_id exactly for every edition in this corpus
        suffix = edition_id

        values = []
        missing = 0
        for goi, conical, version, lang, book, chapter, verse, testament in rows:
            fn = f"{conical:03d}_{book}_{chapter:03d}_{verse:03d}_{suffix}.txt"
            fp = os.path.join(d, fn)
            if not os.path.isfile(fp):
                missing += 1
                continue
            with open(fp, encoding="utf-8") as f:
                text = f.read().strip()
            values.append(
                "({}, {}, {}, {}, {}, {}, {}, {}, {}, {})".format(
                    goi, conical, sql_quote(edition_id), sql_quote(version),
                    sql_quote(lang), sql_quote(book), chapter, verse,
                    sql_quote(testament), sql_quote(text),
                )
            )

        if missing:
            print(f"WARNING: {edition_id}: {missing} rows had no matching flat file", file=sys.stderr)

        out_path = os.path.join(OUT_DIR, f"{edition_id}.sql")
        with open(out_path, "w", encoding="utf-8") as out:
            out.write(f"-- {edition_id}: {len(values)} verses. Generated by sqlite/build_buffet.py\n")
            out.write("INSERT INTO verses (goi, conical, edition_id, version, language_subtag, book, chapter, verse, testament, verse_text) VALUES\n")
            out.write(",\n".join(values))
            out.write(";\n")

        print(f"{edition_id}: wrote {len(values)} rows -> {out_path}")
        total += len(values)

    conn.close()
    print(f"TOTAL: {total}")


if __name__ == "__main__":
    main()
